linters:
  enable-all: true
  disable:
    - cyclop
    - dupl
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - golint
    - ifshort
    - interfacer
    - lll
    - maintidx
    - maligned
    - nestif
    - nlreturn
    - nolintlint
    - scopelint
    - varnamelen
    - whitespace
    - wsl

linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
