builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
