apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-opa-1
  name: nginx-opa-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-opa-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-opa-1
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: pvc-1
status: {}
