linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - forbidigo
    - funlen
    - gocognit
    - gocyclo
    - lll
    - nestif
    - nlreturn
    - whitespace
    - wsl

linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
