apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: exitcodes
  name: exitcodes
spec:
  shareProcessNamespace: true
  containers:
  - image: bespinian/exitcodes:0.0.2
    name: exitcodes
    securityContext:
      privileged: true
    volumeMounts:
      - name: sys
        mountPath: /sys
        readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: sys
      hostPath:
        path: /sys
