// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package livelint

import (
	"context"
	apiv1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/applyconfigurations/core/v1"
	"k8s.io/client-go/rest"
	"sync"
)

// Ensure, that apiv1ServiceInterfaceMock does implement apiv1ServiceInterface.
// If this is not the case, regenerate this file with moq.
var _ apiv1ServiceInterface = &apiv1ServiceInterfaceMock{}

// apiv1ServiceInterfaceMock is a mock implementation of apiv1ServiceInterface.
//
// 	func TestSomethingThatUsesapiv1ServiceInterface(t *testing.T) {
//
// 		// make and configure a mocked apiv1ServiceInterface
// 		mockedapiv1ServiceInterface := &apiv1ServiceInterfaceMock{
// 			ApplyFunc: func(ctx context.Context, service *v1.ServiceApplyConfiguration, opts metav1.ApplyOptions) (*apiv1.Service, error) {
// 				panic("mock out the Apply method")
// 			},
// 			ApplyStatusFunc: func(ctx context.Context, service *v1.ServiceApplyConfiguration, opts metav1.ApplyOptions) (*apiv1.Service, error) {
// 				panic("mock out the ApplyStatus method")
// 			},
// 			CreateFunc: func(ctx context.Context, service *apiv1.Service, opts metav1.CreateOptions) (*apiv1.Service, error) {
// 				panic("mock out the Create method")
// 			},
// 			DeleteFunc: func(ctx context.Context, name string, opts metav1.DeleteOptions) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetFunc: func(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.Service, error) {
// 				panic("mock out the Get method")
// 			},
// 			ListFunc: func(ctx context.Context, opts metav1.ListOptions) (*apiv1.ServiceList, error) {
// 				panic("mock out the List method")
// 			},
// 			PatchFunc: func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*apiv1.Service, error) {
// 				panic("mock out the Patch method")
// 			},
// 			ProxyGetFunc: func(scheme string, name string, port string, path string, params map[string]string) rest.ResponseWrapper {
// 				panic("mock out the ProxyGet method")
// 			},
// 			UpdateFunc: func(ctx context.Context, service *apiv1.Service, opts metav1.UpdateOptions) (*apiv1.Service, error) {
// 				panic("mock out the Update method")
// 			},
// 			UpdateStatusFunc: func(ctx context.Context, service *apiv1.Service, opts metav1.UpdateOptions) (*apiv1.Service, error) {
// 				panic("mock out the UpdateStatus method")
// 			},
// 			WatchFunc: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
// 				panic("mock out the Watch method")
// 			},
// 		}
//
// 		// use mockedapiv1ServiceInterface in code that requires apiv1ServiceInterface
// 		// and then make assertions.
//
// 	}
type apiv1ServiceInterfaceMock struct {
	// ApplyFunc mocks the Apply method.
	ApplyFunc func(ctx context.Context, service *v1.ServiceApplyConfiguration, opts metav1.ApplyOptions) (*apiv1.Service, error)

	// ApplyStatusFunc mocks the ApplyStatus method.
	ApplyStatusFunc func(ctx context.Context, service *v1.ServiceApplyConfiguration, opts metav1.ApplyOptions) (*apiv1.Service, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, service *apiv1.Service, opts metav1.CreateOptions) (*apiv1.Service, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, name string, opts metav1.DeleteOptions) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.Service, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, opts metav1.ListOptions) (*apiv1.ServiceList, error)

	// PatchFunc mocks the Patch method.
	PatchFunc func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*apiv1.Service, error)

	// ProxyGetFunc mocks the ProxyGet method.
	ProxyGetFunc func(scheme string, name string, port string, path string, params map[string]string) rest.ResponseWrapper

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, service *apiv1.Service, opts metav1.UpdateOptions) (*apiv1.Service, error)

	// UpdateStatusFunc mocks the UpdateStatus method.
	UpdateStatusFunc func(ctx context.Context, service *apiv1.Service, opts metav1.UpdateOptions) (*apiv1.Service, error)

	// WatchFunc mocks the Watch method.
	WatchFunc func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)

	// calls tracks calls to the methods.
	calls struct {
		// Apply holds details about calls to the Apply method.
		Apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Service is the service argument value.
			Service *v1.ServiceApplyConfiguration
			// Opts is the opts argument value.
			Opts metav1.ApplyOptions
		}
		// ApplyStatus holds details about calls to the ApplyStatus method.
		ApplyStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Service is the service argument value.
			Service *v1.ServiceApplyConfiguration
			// Opts is the opts argument value.
			Opts metav1.ApplyOptions
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Service is the service argument value.
			Service *apiv1.Service
			// Opts is the opts argument value.
			Opts metav1.CreateOptions
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts metav1.DeleteOptions
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts metav1.GetOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.ListOptions
		}
		// Patch holds details about calls to the Patch method.
		Patch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Pt is the pt argument value.
			Pt types.PatchType
			// Data is the data argument value.
			Data []byte
			// Opts is the opts argument value.
			Opts metav1.PatchOptions
			// Subresources is the subresources argument value.
			Subresources []string
		}
		// ProxyGet holds details about calls to the ProxyGet method.
		ProxyGet []struct {
			// Scheme is the scheme argument value.
			Scheme string
			// Name is the name argument value.
			Name string
			// Port is the port argument value.
			Port string
			// Path is the path argument value.
			Path string
			// Params is the params argument value.
			Params map[string]string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Service is the service argument value.
			Service *apiv1.Service
			// Opts is the opts argument value.
			Opts metav1.UpdateOptions
		}
		// UpdateStatus holds details about calls to the UpdateStatus method.
		UpdateStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Service is the service argument value.
			Service *apiv1.Service
			// Opts is the opts argument value.
			Opts metav1.UpdateOptions
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.ListOptions
		}
	}
	lockApply        sync.RWMutex
	lockApplyStatus  sync.RWMutex
	lockCreate       sync.RWMutex
	lockDelete       sync.RWMutex
	lockGet          sync.RWMutex
	lockList         sync.RWMutex
	lockPatch        sync.RWMutex
	lockProxyGet     sync.RWMutex
	lockUpdate       sync.RWMutex
	lockUpdateStatus sync.RWMutex
	lockWatch        sync.RWMutex
}

// Apply calls ApplyFunc.
func (mock *apiv1ServiceInterfaceMock) Apply(ctx context.Context, service *v1.ServiceApplyConfiguration, opts metav1.ApplyOptions) (*apiv1.Service, error) {
	if mock.ApplyFunc == nil {
		panic("apiv1ServiceInterfaceMock.ApplyFunc: method is nil but apiv1ServiceInterface.Apply was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Service *v1.ServiceApplyConfiguration
		Opts    metav1.ApplyOptions
	}{
		Ctx:     ctx,
		Service: service,
		Opts:    opts,
	}
	mock.lockApply.Lock()
	mock.calls.Apply = append(mock.calls.Apply, callInfo)
	mock.lockApply.Unlock()
	return mock.ApplyFunc(ctx, service, opts)
}

// ApplyCalls gets all the calls that were made to Apply.
// Check the length with:
//     len(mockedapiv1ServiceInterface.ApplyCalls())
func (mock *apiv1ServiceInterfaceMock) ApplyCalls() []struct {
	Ctx     context.Context
	Service *v1.ServiceApplyConfiguration
	Opts    metav1.ApplyOptions
} {
	var calls []struct {
		Ctx     context.Context
		Service *v1.ServiceApplyConfiguration
		Opts    metav1.ApplyOptions
	}
	mock.lockApply.RLock()
	calls = mock.calls.Apply
	mock.lockApply.RUnlock()
	return calls
}

// ApplyStatus calls ApplyStatusFunc.
func (mock *apiv1ServiceInterfaceMock) ApplyStatus(ctx context.Context, service *v1.ServiceApplyConfiguration, opts metav1.ApplyOptions) (*apiv1.Service, error) {
	if mock.ApplyStatusFunc == nil {
		panic("apiv1ServiceInterfaceMock.ApplyStatusFunc: method is nil but apiv1ServiceInterface.ApplyStatus was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Service *v1.ServiceApplyConfiguration
		Opts    metav1.ApplyOptions
	}{
		Ctx:     ctx,
		Service: service,
		Opts:    opts,
	}
	mock.lockApplyStatus.Lock()
	mock.calls.ApplyStatus = append(mock.calls.ApplyStatus, callInfo)
	mock.lockApplyStatus.Unlock()
	return mock.ApplyStatusFunc(ctx, service, opts)
}

// ApplyStatusCalls gets all the calls that were made to ApplyStatus.
// Check the length with:
//     len(mockedapiv1ServiceInterface.ApplyStatusCalls())
func (mock *apiv1ServiceInterfaceMock) ApplyStatusCalls() []struct {
	Ctx     context.Context
	Service *v1.ServiceApplyConfiguration
	Opts    metav1.ApplyOptions
} {
	var calls []struct {
		Ctx     context.Context
		Service *v1.ServiceApplyConfiguration
		Opts    metav1.ApplyOptions
	}
	mock.lockApplyStatus.RLock()
	calls = mock.calls.ApplyStatus
	mock.lockApplyStatus.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *apiv1ServiceInterfaceMock) Create(ctx context.Context, service *apiv1.Service, opts metav1.CreateOptions) (*apiv1.Service, error) {
	if mock.CreateFunc == nil {
		panic("apiv1ServiceInterfaceMock.CreateFunc: method is nil but apiv1ServiceInterface.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Service *apiv1.Service
		Opts    metav1.CreateOptions
	}{
		Ctx:     ctx,
		Service: service,
		Opts:    opts,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, service, opts)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedapiv1ServiceInterface.CreateCalls())
func (mock *apiv1ServiceInterfaceMock) CreateCalls() []struct {
	Ctx     context.Context
	Service *apiv1.Service
	Opts    metav1.CreateOptions
} {
	var calls []struct {
		Ctx     context.Context
		Service *apiv1.Service
		Opts    metav1.CreateOptions
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *apiv1ServiceInterfaceMock) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	if mock.DeleteFunc == nil {
		panic("apiv1ServiceInterfaceMock.DeleteFunc: method is nil but apiv1ServiceInterface.Delete was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Opts metav1.DeleteOptions
	}{
		Ctx:  ctx,
		Name: name,
		Opts: opts,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, name, opts)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedapiv1ServiceInterface.DeleteCalls())
func (mock *apiv1ServiceInterfaceMock) DeleteCalls() []struct {
	Ctx  context.Context
	Name string
	Opts metav1.DeleteOptions
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Opts metav1.DeleteOptions
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *apiv1ServiceInterfaceMock) Get(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.Service, error) {
	if mock.GetFunc == nil {
		panic("apiv1ServiceInterfaceMock.GetFunc: method is nil but apiv1ServiceInterface.Get was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Opts metav1.GetOptions
	}{
		Ctx:  ctx,
		Name: name,
		Opts: opts,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, name, opts)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedapiv1ServiceInterface.GetCalls())
func (mock *apiv1ServiceInterfaceMock) GetCalls() []struct {
	Ctx  context.Context
	Name string
	Opts metav1.GetOptions
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Opts metav1.GetOptions
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *apiv1ServiceInterfaceMock) List(ctx context.Context, opts metav1.ListOptions) (*apiv1.ServiceList, error) {
	if mock.ListFunc == nil {
		panic("apiv1ServiceInterfaceMock.ListFunc: method is nil but apiv1ServiceInterface.List was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, opts)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedapiv1ServiceInterface.ListCalls())
func (mock *apiv1ServiceInterfaceMock) ListCalls() []struct {
	Ctx  context.Context
	Opts metav1.ListOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Patch calls PatchFunc.
func (mock *apiv1ServiceInterfaceMock) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*apiv1.Service, error) {
	if mock.PatchFunc == nil {
		panic("apiv1ServiceInterfaceMock.PatchFunc: method is nil but apiv1ServiceInterface.Patch was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Name         string
		Pt           types.PatchType
		Data         []byte
		Opts         metav1.PatchOptions
		Subresources []string
	}{
		Ctx:          ctx,
		Name:         name,
		Pt:           pt,
		Data:         data,
		Opts:         opts,
		Subresources: subresources,
	}
	mock.lockPatch.Lock()
	mock.calls.Patch = append(mock.calls.Patch, callInfo)
	mock.lockPatch.Unlock()
	return mock.PatchFunc(ctx, name, pt, data, opts, subresources...)
}

// PatchCalls gets all the calls that were made to Patch.
// Check the length with:
//     len(mockedapiv1ServiceInterface.PatchCalls())
func (mock *apiv1ServiceInterfaceMock) PatchCalls() []struct {
	Ctx          context.Context
	Name         string
	Pt           types.PatchType
	Data         []byte
	Opts         metav1.PatchOptions
	Subresources []string
} {
	var calls []struct {
		Ctx          context.Context
		Name         string
		Pt           types.PatchType
		Data         []byte
		Opts         metav1.PatchOptions
		Subresources []string
	}
	mock.lockPatch.RLock()
	calls = mock.calls.Patch
	mock.lockPatch.RUnlock()
	return calls
}

// ProxyGet calls ProxyGetFunc.
func (mock *apiv1ServiceInterfaceMock) ProxyGet(scheme string, name string, port string, path string, params map[string]string) rest.ResponseWrapper {
	if mock.ProxyGetFunc == nil {
		panic("apiv1ServiceInterfaceMock.ProxyGetFunc: method is nil but apiv1ServiceInterface.ProxyGet was just called")
	}
	callInfo := struct {
		Scheme string
		Name   string
		Port   string
		Path   string
		Params map[string]string
	}{
		Scheme: scheme,
		Name:   name,
		Port:   port,
		Path:   path,
		Params: params,
	}
	mock.lockProxyGet.Lock()
	mock.calls.ProxyGet = append(mock.calls.ProxyGet, callInfo)
	mock.lockProxyGet.Unlock()
	return mock.ProxyGetFunc(scheme, name, port, path, params)
}

// ProxyGetCalls gets all the calls that were made to ProxyGet.
// Check the length with:
//     len(mockedapiv1ServiceInterface.ProxyGetCalls())
func (mock *apiv1ServiceInterfaceMock) ProxyGetCalls() []struct {
	Scheme string
	Name   string
	Port   string
	Path   string
	Params map[string]string
} {
	var calls []struct {
		Scheme string
		Name   string
		Port   string
		Path   string
		Params map[string]string
	}
	mock.lockProxyGet.RLock()
	calls = mock.calls.ProxyGet
	mock.lockProxyGet.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *apiv1ServiceInterfaceMock) Update(ctx context.Context, service *apiv1.Service, opts metav1.UpdateOptions) (*apiv1.Service, error) {
	if mock.UpdateFunc == nil {
		panic("apiv1ServiceInterfaceMock.UpdateFunc: method is nil but apiv1ServiceInterface.Update was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Service *apiv1.Service
		Opts    metav1.UpdateOptions
	}{
		Ctx:     ctx,
		Service: service,
		Opts:    opts,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, service, opts)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedapiv1ServiceInterface.UpdateCalls())
func (mock *apiv1ServiceInterfaceMock) UpdateCalls() []struct {
	Ctx     context.Context
	Service *apiv1.Service
	Opts    metav1.UpdateOptions
} {
	var calls []struct {
		Ctx     context.Context
		Service *apiv1.Service
		Opts    metav1.UpdateOptions
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdateStatus calls UpdateStatusFunc.
func (mock *apiv1ServiceInterfaceMock) UpdateStatus(ctx context.Context, service *apiv1.Service, opts metav1.UpdateOptions) (*apiv1.Service, error) {
	if mock.UpdateStatusFunc == nil {
		panic("apiv1ServiceInterfaceMock.UpdateStatusFunc: method is nil but apiv1ServiceInterface.UpdateStatus was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Service *apiv1.Service
		Opts    metav1.UpdateOptions
	}{
		Ctx:     ctx,
		Service: service,
		Opts:    opts,
	}
	mock.lockUpdateStatus.Lock()
	mock.calls.UpdateStatus = append(mock.calls.UpdateStatus, callInfo)
	mock.lockUpdateStatus.Unlock()
	return mock.UpdateStatusFunc(ctx, service, opts)
}

// UpdateStatusCalls gets all the calls that were made to UpdateStatus.
// Check the length with:
//     len(mockedapiv1ServiceInterface.UpdateStatusCalls())
func (mock *apiv1ServiceInterfaceMock) UpdateStatusCalls() []struct {
	Ctx     context.Context
	Service *apiv1.Service
	Opts    metav1.UpdateOptions
} {
	var calls []struct {
		Ctx     context.Context
		Service *apiv1.Service
		Opts    metav1.UpdateOptions
	}
	mock.lockUpdateStatus.RLock()
	calls = mock.calls.UpdateStatus
	mock.lockUpdateStatus.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *apiv1ServiceInterfaceMock) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	if mock.WatchFunc == nil {
		panic("apiv1ServiceInterfaceMock.WatchFunc: method is nil but apiv1ServiceInterface.Watch was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	mock.lockWatch.Unlock()
	return mock.WatchFunc(ctx, opts)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//     len(mockedapiv1ServiceInterface.WatchCalls())
func (mock *apiv1ServiceInterfaceMock) WatchCalls() []struct {
	Ctx  context.Context
	Opts metav1.ListOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}
	mock.lockWatch.RLock()
	calls = mock.calls.Watch
	mock.lockWatch.RUnlock()
	return calls
}
