// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package livelint

import (
	"context"
	apiv1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/applyconfigurations/core/v1"
	"sync"
)

// Ensure, that apiv1EndpointsInterfaceMock does implement apiv1EndpointsInterface.
// If this is not the case, regenerate this file with moq.
var _ apiv1EndpointsInterface = &apiv1EndpointsInterfaceMock{}

// apiv1EndpointsInterfaceMock is a mock implementation of apiv1EndpointsInterface.
//
// 	func TestSomethingThatUsesapiv1EndpointsInterface(t *testing.T) {
//
// 		// make and configure a mocked apiv1EndpointsInterface
// 		mockedapiv1EndpointsInterface := &apiv1EndpointsInterfaceMock{
// 			ApplyFunc: func(ctx context.Context, endpoints *v1.EndpointsApplyConfiguration, opts metav1.ApplyOptions) (*apiv1.Endpoints, error) {
// 				panic("mock out the Apply method")
// 			},
// 			CreateFunc: func(ctx context.Context, endpoints *apiv1.Endpoints, opts metav1.CreateOptions) (*apiv1.Endpoints, error) {
// 				panic("mock out the Create method")
// 			},
// 			DeleteFunc: func(ctx context.Context, name string, opts metav1.DeleteOptions) error {
// 				panic("mock out the Delete method")
// 			},
// 			DeleteCollectionFunc: func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
// 				panic("mock out the DeleteCollection method")
// 			},
// 			GetFunc: func(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.Endpoints, error) {
// 				panic("mock out the Get method")
// 			},
// 			ListFunc: func(ctx context.Context, opts metav1.ListOptions) (*apiv1.EndpointsList, error) {
// 				panic("mock out the List method")
// 			},
// 			PatchFunc: func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*apiv1.Endpoints, error) {
// 				panic("mock out the Patch method")
// 			},
// 			UpdateFunc: func(ctx context.Context, endpoints *apiv1.Endpoints, opts metav1.UpdateOptions) (*apiv1.Endpoints, error) {
// 				panic("mock out the Update method")
// 			},
// 			WatchFunc: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
// 				panic("mock out the Watch method")
// 			},
// 		}
//
// 		// use mockedapiv1EndpointsInterface in code that requires apiv1EndpointsInterface
// 		// and then make assertions.
//
// 	}
type apiv1EndpointsInterfaceMock struct {
	// ApplyFunc mocks the Apply method.
	ApplyFunc func(ctx context.Context, endpoints *v1.EndpointsApplyConfiguration, opts metav1.ApplyOptions) (*apiv1.Endpoints, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, endpoints *apiv1.Endpoints, opts metav1.CreateOptions) (*apiv1.Endpoints, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, name string, opts metav1.DeleteOptions) error

	// DeleteCollectionFunc mocks the DeleteCollection method.
	DeleteCollectionFunc func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.Endpoints, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, opts metav1.ListOptions) (*apiv1.EndpointsList, error)

	// PatchFunc mocks the Patch method.
	PatchFunc func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*apiv1.Endpoints, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, endpoints *apiv1.Endpoints, opts metav1.UpdateOptions) (*apiv1.Endpoints, error)

	// WatchFunc mocks the Watch method.
	WatchFunc func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)

	// calls tracks calls to the methods.
	calls struct {
		// Apply holds details about calls to the Apply method.
		Apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Endpoints is the endpoints argument value.
			Endpoints *v1.EndpointsApplyConfiguration
			// Opts is the opts argument value.
			Opts metav1.ApplyOptions
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Endpoints is the endpoints argument value.
			Endpoints *apiv1.Endpoints
			// Opts is the opts argument value.
			Opts metav1.CreateOptions
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts metav1.DeleteOptions
		}
		// DeleteCollection holds details about calls to the DeleteCollection method.
		DeleteCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.DeleteOptions
			// ListOpts is the listOpts argument value.
			ListOpts metav1.ListOptions
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts metav1.GetOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.ListOptions
		}
		// Patch holds details about calls to the Patch method.
		Patch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Pt is the pt argument value.
			Pt types.PatchType
			// Data is the data argument value.
			Data []byte
			// Opts is the opts argument value.
			Opts metav1.PatchOptions
			// Subresources is the subresources argument value.
			Subresources []string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Endpoints is the endpoints argument value.
			Endpoints *apiv1.Endpoints
			// Opts is the opts argument value.
			Opts metav1.UpdateOptions
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.ListOptions
		}
	}
	lockApply            sync.RWMutex
	lockCreate           sync.RWMutex
	lockDelete           sync.RWMutex
	lockDeleteCollection sync.RWMutex
	lockGet              sync.RWMutex
	lockList             sync.RWMutex
	lockPatch            sync.RWMutex
	lockUpdate           sync.RWMutex
	lockWatch            sync.RWMutex
}

// Apply calls ApplyFunc.
func (mock *apiv1EndpointsInterfaceMock) Apply(ctx context.Context, endpoints *v1.EndpointsApplyConfiguration, opts metav1.ApplyOptions) (*apiv1.Endpoints, error) {
	if mock.ApplyFunc == nil {
		panic("apiv1EndpointsInterfaceMock.ApplyFunc: method is nil but apiv1EndpointsInterface.Apply was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Endpoints *v1.EndpointsApplyConfiguration
		Opts      metav1.ApplyOptions
	}{
		Ctx:       ctx,
		Endpoints: endpoints,
		Opts:      opts,
	}
	mock.lockApply.Lock()
	mock.calls.Apply = append(mock.calls.Apply, callInfo)
	mock.lockApply.Unlock()
	return mock.ApplyFunc(ctx, endpoints, opts)
}

// ApplyCalls gets all the calls that were made to Apply.
// Check the length with:
//     len(mockedapiv1EndpointsInterface.ApplyCalls())
func (mock *apiv1EndpointsInterfaceMock) ApplyCalls() []struct {
	Ctx       context.Context
	Endpoints *v1.EndpointsApplyConfiguration
	Opts      metav1.ApplyOptions
} {
	var calls []struct {
		Ctx       context.Context
		Endpoints *v1.EndpointsApplyConfiguration
		Opts      metav1.ApplyOptions
	}
	mock.lockApply.RLock()
	calls = mock.calls.Apply
	mock.lockApply.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *apiv1EndpointsInterfaceMock) Create(ctx context.Context, endpoints *apiv1.Endpoints, opts metav1.CreateOptions) (*apiv1.Endpoints, error) {
	if mock.CreateFunc == nil {
		panic("apiv1EndpointsInterfaceMock.CreateFunc: method is nil but apiv1EndpointsInterface.Create was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Endpoints *apiv1.Endpoints
		Opts      metav1.CreateOptions
	}{
		Ctx:       ctx,
		Endpoints: endpoints,
		Opts:      opts,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, endpoints, opts)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedapiv1EndpointsInterface.CreateCalls())
func (mock *apiv1EndpointsInterfaceMock) CreateCalls() []struct {
	Ctx       context.Context
	Endpoints *apiv1.Endpoints
	Opts      metav1.CreateOptions
} {
	var calls []struct {
		Ctx       context.Context
		Endpoints *apiv1.Endpoints
		Opts      metav1.CreateOptions
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *apiv1EndpointsInterfaceMock) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	if mock.DeleteFunc == nil {
		panic("apiv1EndpointsInterfaceMock.DeleteFunc: method is nil but apiv1EndpointsInterface.Delete was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Opts metav1.DeleteOptions
	}{
		Ctx:  ctx,
		Name: name,
		Opts: opts,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, name, opts)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedapiv1EndpointsInterface.DeleteCalls())
func (mock *apiv1EndpointsInterfaceMock) DeleteCalls() []struct {
	Ctx  context.Context
	Name string
	Opts metav1.DeleteOptions
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Opts metav1.DeleteOptions
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeleteCollection calls DeleteCollectionFunc.
func (mock *apiv1EndpointsInterfaceMock) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	if mock.DeleteCollectionFunc == nil {
		panic("apiv1EndpointsInterfaceMock.DeleteCollectionFunc: method is nil but apiv1EndpointsInterface.DeleteCollection was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Opts     metav1.DeleteOptions
		ListOpts metav1.ListOptions
	}{
		Ctx:      ctx,
		Opts:     opts,
		ListOpts: listOpts,
	}
	mock.lockDeleteCollection.Lock()
	mock.calls.DeleteCollection = append(mock.calls.DeleteCollection, callInfo)
	mock.lockDeleteCollection.Unlock()
	return mock.DeleteCollectionFunc(ctx, opts, listOpts)
}

// DeleteCollectionCalls gets all the calls that were made to DeleteCollection.
// Check the length with:
//     len(mockedapiv1EndpointsInterface.DeleteCollectionCalls())
func (mock *apiv1EndpointsInterfaceMock) DeleteCollectionCalls() []struct {
	Ctx      context.Context
	Opts     metav1.DeleteOptions
	ListOpts metav1.ListOptions
} {
	var calls []struct {
		Ctx      context.Context
		Opts     metav1.DeleteOptions
		ListOpts metav1.ListOptions
	}
	mock.lockDeleteCollection.RLock()
	calls = mock.calls.DeleteCollection
	mock.lockDeleteCollection.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *apiv1EndpointsInterfaceMock) Get(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.Endpoints, error) {
	if mock.GetFunc == nil {
		panic("apiv1EndpointsInterfaceMock.GetFunc: method is nil but apiv1EndpointsInterface.Get was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Opts metav1.GetOptions
	}{
		Ctx:  ctx,
		Name: name,
		Opts: opts,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, name, opts)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedapiv1EndpointsInterface.GetCalls())
func (mock *apiv1EndpointsInterfaceMock) GetCalls() []struct {
	Ctx  context.Context
	Name string
	Opts metav1.GetOptions
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Opts metav1.GetOptions
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *apiv1EndpointsInterfaceMock) List(ctx context.Context, opts metav1.ListOptions) (*apiv1.EndpointsList, error) {
	if mock.ListFunc == nil {
		panic("apiv1EndpointsInterfaceMock.ListFunc: method is nil but apiv1EndpointsInterface.List was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, opts)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedapiv1EndpointsInterface.ListCalls())
func (mock *apiv1EndpointsInterfaceMock) ListCalls() []struct {
	Ctx  context.Context
	Opts metav1.ListOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Patch calls PatchFunc.
func (mock *apiv1EndpointsInterfaceMock) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*apiv1.Endpoints, error) {
	if mock.PatchFunc == nil {
		panic("apiv1EndpointsInterfaceMock.PatchFunc: method is nil but apiv1EndpointsInterface.Patch was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Name         string
		Pt           types.PatchType
		Data         []byte
		Opts         metav1.PatchOptions
		Subresources []string
	}{
		Ctx:          ctx,
		Name:         name,
		Pt:           pt,
		Data:         data,
		Opts:         opts,
		Subresources: subresources,
	}
	mock.lockPatch.Lock()
	mock.calls.Patch = append(mock.calls.Patch, callInfo)
	mock.lockPatch.Unlock()
	return mock.PatchFunc(ctx, name, pt, data, opts, subresources...)
}

// PatchCalls gets all the calls that were made to Patch.
// Check the length with:
//     len(mockedapiv1EndpointsInterface.PatchCalls())
func (mock *apiv1EndpointsInterfaceMock) PatchCalls() []struct {
	Ctx          context.Context
	Name         string
	Pt           types.PatchType
	Data         []byte
	Opts         metav1.PatchOptions
	Subresources []string
} {
	var calls []struct {
		Ctx          context.Context
		Name         string
		Pt           types.PatchType
		Data         []byte
		Opts         metav1.PatchOptions
		Subresources []string
	}
	mock.lockPatch.RLock()
	calls = mock.calls.Patch
	mock.lockPatch.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *apiv1EndpointsInterfaceMock) Update(ctx context.Context, endpoints *apiv1.Endpoints, opts metav1.UpdateOptions) (*apiv1.Endpoints, error) {
	if mock.UpdateFunc == nil {
		panic("apiv1EndpointsInterfaceMock.UpdateFunc: method is nil but apiv1EndpointsInterface.Update was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Endpoints *apiv1.Endpoints
		Opts      metav1.UpdateOptions
	}{
		Ctx:       ctx,
		Endpoints: endpoints,
		Opts:      opts,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, endpoints, opts)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedapiv1EndpointsInterface.UpdateCalls())
func (mock *apiv1EndpointsInterfaceMock) UpdateCalls() []struct {
	Ctx       context.Context
	Endpoints *apiv1.Endpoints
	Opts      metav1.UpdateOptions
} {
	var calls []struct {
		Ctx       context.Context
		Endpoints *apiv1.Endpoints
		Opts      metav1.UpdateOptions
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *apiv1EndpointsInterfaceMock) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	if mock.WatchFunc == nil {
		panic("apiv1EndpointsInterfaceMock.WatchFunc: method is nil but apiv1EndpointsInterface.Watch was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	mock.lockWatch.Unlock()
	return mock.WatchFunc(ctx, opts)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//     len(mockedapiv1EndpointsInterface.WatchCalls())
func (mock *apiv1EndpointsInterfaceMock) WatchCalls() []struct {
	Ctx  context.Context
	Opts metav1.ListOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}
	mock.lockWatch.RLock()
	calls = mock.calls.Watch
	mock.lockWatch.RUnlock()
	return calls
}
