// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package livelint

import (
	"context"
	"sync"

	appsv1 "k8s.io/api/apps/v1"
	v1 "k8s.io/api/autoscaling/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	configappsv1 "k8s.io/client-go/applyconfigurations/apps/v1"
	autoscalingv1 "k8s.io/client-go/applyconfigurations/autoscaling/v1"
)

// Ensure, that replicaSetInterfaceMock does implement replicaSetInterface.
// If this is not the case, regenerate this file with moq.
var _ replicaSetInterface = &replicaSetInterfaceMock{}

// replicaSetInterfaceMock is a mock implementation of replicaSetInterface.
//
// 	func TestSomethingThatUsesreplicaSetInterface(t *testing.T) {
//
// 		// make and configure a mocked replicaSetInterface
// 		mockedreplicaSetInterface := &replicaSetInterfaceMock{
// 			ApplyFunc: func(ctx context.Context, replicaSet *appsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*appsv1.ReplicaSet, error) {
// 				panic("mock out the Apply method")
// 			},
// 			ApplyScaleFunc: func(ctx context.Context, replicaSetName string, scale *autoscalingv1.ScaleApplyConfiguration, opts metav1.ApplyOptions) (*v1.Scale, error) {
// 				panic("mock out the ApplyScale method")
// 			},
// 			ApplyStatusFunc: func(ctx context.Context, replicaSet *appsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*appsv1.ReplicaSet, error) {
// 				panic("mock out the ApplyStatus method")
// 			},
// 			CreateFunc: func(ctx context.Context, replicaSet *appsv1.ReplicaSet, opts metav1.CreateOptions) (*appsv1.ReplicaSet, error) {
// 				panic("mock out the Create method")
// 			},
// 			DeleteFunc: func(ctx context.Context, name string, opts metav1.DeleteOptions) error {
// 				panic("mock out the Delete method")
// 			},
// 			DeleteCollectionFunc: func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
// 				panic("mock out the DeleteCollection method")
// 			},
// 			GetFunc: func(ctx context.Context, name string, opts metav1.GetOptions) (*appsv1.ReplicaSet, error) {
// 				panic("mock out the Get method")
// 			},
// 			GetScaleFunc: func(ctx context.Context, replicaSetName string, options metav1.GetOptions) (*v1.Scale, error) {
// 				panic("mock out the GetScale method")
// 			},
// 			ListFunc: func(ctx context.Context, opts metav1.ListOptions) (*appsv1.ReplicaSetList, error) {
// 				panic("mock out the List method")
// 			},
// 			PatchFunc: func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*appsv1.ReplicaSet, error) {
// 				panic("mock out the Patch method")
// 			},
// 			UpdateFunc: func(ctx context.Context, replicaSet *appsv1.ReplicaSet, opts metav1.UpdateOptions) (*appsv1.ReplicaSet, error) {
// 				panic("mock out the Update method")
// 			},
// 			UpdateScaleFunc: func(ctx context.Context, replicaSetName string, scale *v1.Scale, opts metav1.UpdateOptions) (*v1.Scale, error) {
// 				panic("mock out the UpdateScale method")
// 			},
// 			UpdateStatusFunc: func(ctx context.Context, replicaSet *appsv1.ReplicaSet, opts metav1.UpdateOptions) (*appsv1.ReplicaSet, error) {
// 				panic("mock out the UpdateStatus method")
// 			},
// 			WatchFunc: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
// 				panic("mock out the Watch method")
// 			},
// 		}
//
// 		// use mockedreplicaSetInterface in code that requires replicaSetInterface
// 		// and then make assertions.
//
// 	}
type replicaSetInterfaceMock struct {
	// ApplyFunc mocks the Apply method.
	ApplyFunc func(ctx context.Context, replicaSet *configappsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*appsv1.ReplicaSet, error)

	// ApplyScaleFunc mocks the ApplyScale method.
	ApplyScaleFunc func(ctx context.Context, replicaSetName string, scale *autoscalingv1.ScaleApplyConfiguration, opts metav1.ApplyOptions) (*v1.Scale, error)

	// ApplyStatusFunc mocks the ApplyStatus method.
	ApplyStatusFunc func(ctx context.Context, replicaSet *configappsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*appsv1.ReplicaSet, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, replicaSet *appsv1.ReplicaSet, opts metav1.CreateOptions) (*appsv1.ReplicaSet, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, name string, opts metav1.DeleteOptions) error

	// DeleteCollectionFunc mocks the DeleteCollection method.
	DeleteCollectionFunc func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, name string, opts metav1.GetOptions) (*appsv1.ReplicaSet, error)

	// GetScaleFunc mocks the GetScale method.
	GetScaleFunc func(ctx context.Context, replicaSetName string, options metav1.GetOptions) (*v1.Scale, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, opts metav1.ListOptions) (*appsv1.ReplicaSetList, error)

	// PatchFunc mocks the Patch method.
	PatchFunc func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*appsv1.ReplicaSet, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, replicaSet *appsv1.ReplicaSet, opts metav1.UpdateOptions) (*appsv1.ReplicaSet, error)

	// UpdateScaleFunc mocks the UpdateScale method.
	UpdateScaleFunc func(ctx context.Context, replicaSetName string, scale *v1.Scale, opts metav1.UpdateOptions) (*v1.Scale, error)

	// UpdateStatusFunc mocks the UpdateStatus method.
	UpdateStatusFunc func(ctx context.Context, replicaSet *appsv1.ReplicaSet, opts metav1.UpdateOptions) (*appsv1.ReplicaSet, error)

	// WatchFunc mocks the Watch method.
	WatchFunc func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)

	// calls tracks calls to the methods.
	calls struct {
		// Apply holds details about calls to the Apply method.
		Apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSet is the replicaSet argument value.
			ReplicaSet *configappsv1.ReplicaSetApplyConfiguration
			// Opts is the opts argument value.
			Opts metav1.ApplyOptions
		}
		// ApplyScale holds details about calls to the ApplyScale method.
		ApplyScale []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSetName is the replicaSetName argument value.
			ReplicaSetName string
			// Scale is the scale argument value.
			Scale *autoscalingv1.ScaleApplyConfiguration
			// Opts is the opts argument value.
			Opts metav1.ApplyOptions
		}
		// ApplyStatus holds details about calls to the ApplyStatus method.
		ApplyStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSet is the replicaSet argument value.
			ReplicaSet *configappsv1.ReplicaSetApplyConfiguration
			// Opts is the opts argument value.
			Opts metav1.ApplyOptions
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSet is the replicaSet argument value.
			ReplicaSet *appsv1.ReplicaSet
			// Opts is the opts argument value.
			Opts metav1.CreateOptions
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts metav1.DeleteOptions
		}
		// DeleteCollection holds details about calls to the DeleteCollection method.
		DeleteCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.DeleteOptions
			// ListOpts is the listOpts argument value.
			ListOpts metav1.ListOptions
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts metav1.GetOptions
		}
		// GetScale holds details about calls to the GetScale method.
		GetScale []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSetName is the replicaSetName argument value.
			ReplicaSetName string
			// Options is the options argument value.
			Options metav1.GetOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.ListOptions
		}
		// Patch holds details about calls to the Patch method.
		Patch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Pt is the pt argument value.
			Pt types.PatchType
			// Data is the data argument value.
			Data []byte
			// Opts is the opts argument value.
			Opts metav1.PatchOptions
			// Subresources is the subresources argument value.
			Subresources []string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSet is the replicaSet argument value.
			ReplicaSet *appsv1.ReplicaSet
			// Opts is the opts argument value.
			Opts metav1.UpdateOptions
		}
		// UpdateScale holds details about calls to the UpdateScale method.
		UpdateScale []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSetName is the replicaSetName argument value.
			ReplicaSetName string
			// Scale is the scale argument value.
			Scale *v1.Scale
			// Opts is the opts argument value.
			Opts metav1.UpdateOptions
		}
		// UpdateStatus holds details about calls to the UpdateStatus method.
		UpdateStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSet is the replicaSet argument value.
			ReplicaSet *appsv1.ReplicaSet
			// Opts is the opts argument value.
			Opts metav1.UpdateOptions
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.ListOptions
		}
	}
	lockApply            sync.RWMutex
	lockApplyScale       sync.RWMutex
	lockApplyStatus      sync.RWMutex
	lockCreate           sync.RWMutex
	lockDelete           sync.RWMutex
	lockDeleteCollection sync.RWMutex
	lockGet              sync.RWMutex
	lockGetScale         sync.RWMutex
	lockList             sync.RWMutex
	lockPatch            sync.RWMutex
	lockUpdate           sync.RWMutex
	lockUpdateScale      sync.RWMutex
	lockUpdateStatus     sync.RWMutex
	lockWatch            sync.RWMutex
}

// Apply calls ApplyFunc.
func (mock *replicaSetInterfaceMock) Apply(ctx context.Context, replicaSet *configappsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*appsv1.ReplicaSet, error) {
	if mock.ApplyFunc == nil {
		panic("replicaSetInterfaceMock.ApplyFunc: method is nil but replicaSetInterface.Apply was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ReplicaSet *configappsv1.ReplicaSetApplyConfiguration
		Opts       metav1.ApplyOptions
	}{
		Ctx:        ctx,
		ReplicaSet: replicaSet,
		Opts:       opts,
	}
	mock.lockApply.Lock()
	mock.calls.Apply = append(mock.calls.Apply, callInfo)
	mock.lockApply.Unlock()
	return mock.ApplyFunc(ctx, replicaSet, opts)
}

// ApplyCalls gets all the calls that were made to Apply.
// Check the length with:
//     len(mockedreplicaSetInterface.ApplyCalls())
func (mock *replicaSetInterfaceMock) ApplyCalls() []struct {
	Ctx        context.Context
	ReplicaSet *configappsv1.ReplicaSetApplyConfiguration
	Opts       metav1.ApplyOptions
} {
	var calls []struct {
		Ctx        context.Context
		ReplicaSet *configappsv1.ReplicaSetApplyConfiguration
		Opts       metav1.ApplyOptions
	}
	mock.lockApply.RLock()
	calls = mock.calls.Apply
	mock.lockApply.RUnlock()
	return calls
}

// ApplyScale calls ApplyScaleFunc.
func (mock *replicaSetInterfaceMock) ApplyScale(ctx context.Context, replicaSetName string, scale *autoscalingv1.ScaleApplyConfiguration, opts metav1.ApplyOptions) (*v1.Scale, error) {
	if mock.ApplyScaleFunc == nil {
		panic("replicaSetInterfaceMock.ApplyScaleFunc: method is nil but replicaSetInterface.ApplyScale was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ReplicaSetName string
		Scale          *autoscalingv1.ScaleApplyConfiguration
		Opts           metav1.ApplyOptions
	}{
		Ctx:            ctx,
		ReplicaSetName: replicaSetName,
		Scale:          scale,
		Opts:           opts,
	}
	mock.lockApplyScale.Lock()
	mock.calls.ApplyScale = append(mock.calls.ApplyScale, callInfo)
	mock.lockApplyScale.Unlock()
	return mock.ApplyScaleFunc(ctx, replicaSetName, scale, opts)
}

// ApplyScaleCalls gets all the calls that were made to ApplyScale.
// Check the length with:
//     len(mockedreplicaSetInterface.ApplyScaleCalls())
func (mock *replicaSetInterfaceMock) ApplyScaleCalls() []struct {
	Ctx            context.Context
	ReplicaSetName string
	Scale          *autoscalingv1.ScaleApplyConfiguration
	Opts           metav1.ApplyOptions
} {
	var calls []struct {
		Ctx            context.Context
		ReplicaSetName string
		Scale          *autoscalingv1.ScaleApplyConfiguration
		Opts           metav1.ApplyOptions
	}
	mock.lockApplyScale.RLock()
	calls = mock.calls.ApplyScale
	mock.lockApplyScale.RUnlock()
	return calls
}

// ApplyStatus calls ApplyStatusFunc.
func (mock *replicaSetInterfaceMock) ApplyStatus(ctx context.Context, replicaSet *configappsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*appsv1.ReplicaSet, error) {
	if mock.ApplyStatusFunc == nil {
		panic("replicaSetInterfaceMock.ApplyStatusFunc: method is nil but replicaSetInterface.ApplyStatus was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ReplicaSet *configappsv1.ReplicaSetApplyConfiguration
		Opts       metav1.ApplyOptions
	}{
		Ctx:        ctx,
		ReplicaSet: replicaSet,
		Opts:       opts,
	}
	mock.lockApplyStatus.Lock()
	mock.calls.ApplyStatus = append(mock.calls.ApplyStatus, callInfo)
	mock.lockApplyStatus.Unlock()
	return mock.ApplyStatusFunc(ctx, replicaSet, opts)
}

// ApplyStatusCalls gets all the calls that were made to ApplyStatus.
// Check the length with:
//     len(mockedreplicaSetInterface.ApplyStatusCalls())
func (mock *replicaSetInterfaceMock) ApplyStatusCalls() []struct {
	Ctx        context.Context
	ReplicaSet *configappsv1.ReplicaSetApplyConfiguration
	Opts       metav1.ApplyOptions
} {
	var calls []struct {
		Ctx        context.Context
		ReplicaSet *configappsv1.ReplicaSetApplyConfiguration
		Opts       metav1.ApplyOptions
	}
	mock.lockApplyStatus.RLock()
	calls = mock.calls.ApplyStatus
	mock.lockApplyStatus.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *replicaSetInterfaceMock) Create(ctx context.Context, replicaSet *appsv1.ReplicaSet, opts metav1.CreateOptions) (*appsv1.ReplicaSet, error) {
	if mock.CreateFunc == nil {
		panic("replicaSetInterfaceMock.CreateFunc: method is nil but replicaSetInterface.Create was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ReplicaSet *appsv1.ReplicaSet
		Opts       metav1.CreateOptions
	}{
		Ctx:        ctx,
		ReplicaSet: replicaSet,
		Opts:       opts,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, replicaSet, opts)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedreplicaSetInterface.CreateCalls())
func (mock *replicaSetInterfaceMock) CreateCalls() []struct {
	Ctx        context.Context
	ReplicaSet *appsv1.ReplicaSet
	Opts       metav1.CreateOptions
} {
	var calls []struct {
		Ctx        context.Context
		ReplicaSet *appsv1.ReplicaSet
		Opts       metav1.CreateOptions
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *replicaSetInterfaceMock) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	if mock.DeleteFunc == nil {
		panic("replicaSetInterfaceMock.DeleteFunc: method is nil but replicaSetInterface.Delete was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Opts metav1.DeleteOptions
	}{
		Ctx:  ctx,
		Name: name,
		Opts: opts,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, name, opts)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedreplicaSetInterface.DeleteCalls())
func (mock *replicaSetInterfaceMock) DeleteCalls() []struct {
	Ctx  context.Context
	Name string
	Opts metav1.DeleteOptions
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Opts metav1.DeleteOptions
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeleteCollection calls DeleteCollectionFunc.
func (mock *replicaSetInterfaceMock) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	if mock.DeleteCollectionFunc == nil {
		panic("replicaSetInterfaceMock.DeleteCollectionFunc: method is nil but replicaSetInterface.DeleteCollection was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Opts     metav1.DeleteOptions
		ListOpts metav1.ListOptions
	}{
		Ctx:      ctx,
		Opts:     opts,
		ListOpts: listOpts,
	}
	mock.lockDeleteCollection.Lock()
	mock.calls.DeleteCollection = append(mock.calls.DeleteCollection, callInfo)
	mock.lockDeleteCollection.Unlock()
	return mock.DeleteCollectionFunc(ctx, opts, listOpts)
}

// DeleteCollectionCalls gets all the calls that were made to DeleteCollection.
// Check the length with:
//     len(mockedreplicaSetInterface.DeleteCollectionCalls())
func (mock *replicaSetInterfaceMock) DeleteCollectionCalls() []struct {
	Ctx      context.Context
	Opts     metav1.DeleteOptions
	ListOpts metav1.ListOptions
} {
	var calls []struct {
		Ctx      context.Context
		Opts     metav1.DeleteOptions
		ListOpts metav1.ListOptions
	}
	mock.lockDeleteCollection.RLock()
	calls = mock.calls.DeleteCollection
	mock.lockDeleteCollection.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *replicaSetInterfaceMock) Get(ctx context.Context, name string, opts metav1.GetOptions) (*appsv1.ReplicaSet, error) {
	if mock.GetFunc == nil {
		panic("replicaSetInterfaceMock.GetFunc: method is nil but replicaSetInterface.Get was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Opts metav1.GetOptions
	}{
		Ctx:  ctx,
		Name: name,
		Opts: opts,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, name, opts)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedreplicaSetInterface.GetCalls())
func (mock *replicaSetInterfaceMock) GetCalls() []struct {
	Ctx  context.Context
	Name string
	Opts metav1.GetOptions
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Opts metav1.GetOptions
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetScale calls GetScaleFunc.
func (mock *replicaSetInterfaceMock) GetScale(ctx context.Context, replicaSetName string, options metav1.GetOptions) (*v1.Scale, error) {
	if mock.GetScaleFunc == nil {
		panic("replicaSetInterfaceMock.GetScaleFunc: method is nil but replicaSetInterface.GetScale was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ReplicaSetName string
		Options        metav1.GetOptions
	}{
		Ctx:            ctx,
		ReplicaSetName: replicaSetName,
		Options:        options,
	}
	mock.lockGetScale.Lock()
	mock.calls.GetScale = append(mock.calls.GetScale, callInfo)
	mock.lockGetScale.Unlock()
	return mock.GetScaleFunc(ctx, replicaSetName, options)
}

// GetScaleCalls gets all the calls that were made to GetScale.
// Check the length with:
//     len(mockedreplicaSetInterface.GetScaleCalls())
func (mock *replicaSetInterfaceMock) GetScaleCalls() []struct {
	Ctx            context.Context
	ReplicaSetName string
	Options        metav1.GetOptions
} {
	var calls []struct {
		Ctx            context.Context
		ReplicaSetName string
		Options        metav1.GetOptions
	}
	mock.lockGetScale.RLock()
	calls = mock.calls.GetScale
	mock.lockGetScale.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *replicaSetInterfaceMock) List(ctx context.Context, opts metav1.ListOptions) (*appsv1.ReplicaSetList, error) {
	if mock.ListFunc == nil {
		panic("replicaSetInterfaceMock.ListFunc: method is nil but replicaSetInterface.List was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, opts)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedreplicaSetInterface.ListCalls())
func (mock *replicaSetInterfaceMock) ListCalls() []struct {
	Ctx  context.Context
	Opts metav1.ListOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Patch calls PatchFunc.
func (mock *replicaSetInterfaceMock) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*appsv1.ReplicaSet, error) {
	if mock.PatchFunc == nil {
		panic("replicaSetInterfaceMock.PatchFunc: method is nil but replicaSetInterface.Patch was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Name         string
		Pt           types.PatchType
		Data         []byte
		Opts         metav1.PatchOptions
		Subresources []string
	}{
		Ctx:          ctx,
		Name:         name,
		Pt:           pt,
		Data:         data,
		Opts:         opts,
		Subresources: subresources,
	}
	mock.lockPatch.Lock()
	mock.calls.Patch = append(mock.calls.Patch, callInfo)
	mock.lockPatch.Unlock()
	return mock.PatchFunc(ctx, name, pt, data, opts, subresources...)
}

// PatchCalls gets all the calls that were made to Patch.
// Check the length with:
//     len(mockedreplicaSetInterface.PatchCalls())
func (mock *replicaSetInterfaceMock) PatchCalls() []struct {
	Ctx          context.Context
	Name         string
	Pt           types.PatchType
	Data         []byte
	Opts         metav1.PatchOptions
	Subresources []string
} {
	var calls []struct {
		Ctx          context.Context
		Name         string
		Pt           types.PatchType
		Data         []byte
		Opts         metav1.PatchOptions
		Subresources []string
	}
	mock.lockPatch.RLock()
	calls = mock.calls.Patch
	mock.lockPatch.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *replicaSetInterfaceMock) Update(ctx context.Context, replicaSet *appsv1.ReplicaSet, opts metav1.UpdateOptions) (*appsv1.ReplicaSet, error) {
	if mock.UpdateFunc == nil {
		panic("replicaSetInterfaceMock.UpdateFunc: method is nil but replicaSetInterface.Update was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ReplicaSet *appsv1.ReplicaSet
		Opts       metav1.UpdateOptions
	}{
		Ctx:        ctx,
		ReplicaSet: replicaSet,
		Opts:       opts,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, replicaSet, opts)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedreplicaSetInterface.UpdateCalls())
func (mock *replicaSetInterfaceMock) UpdateCalls() []struct {
	Ctx        context.Context
	ReplicaSet *appsv1.ReplicaSet
	Opts       metav1.UpdateOptions
} {
	var calls []struct {
		Ctx        context.Context
		ReplicaSet *appsv1.ReplicaSet
		Opts       metav1.UpdateOptions
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdateScale calls UpdateScaleFunc.
func (mock *replicaSetInterfaceMock) UpdateScale(ctx context.Context, replicaSetName string, scale *v1.Scale, opts metav1.UpdateOptions) (*v1.Scale, error) {
	if mock.UpdateScaleFunc == nil {
		panic("replicaSetInterfaceMock.UpdateScaleFunc: method is nil but replicaSetInterface.UpdateScale was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ReplicaSetName string
		Scale          *v1.Scale
		Opts           metav1.UpdateOptions
	}{
		Ctx:            ctx,
		ReplicaSetName: replicaSetName,
		Scale:          scale,
		Opts:           opts,
	}
	mock.lockUpdateScale.Lock()
	mock.calls.UpdateScale = append(mock.calls.UpdateScale, callInfo)
	mock.lockUpdateScale.Unlock()
	return mock.UpdateScaleFunc(ctx, replicaSetName, scale, opts)
}

// UpdateScaleCalls gets all the calls that were made to UpdateScale.
// Check the length with:
//     len(mockedreplicaSetInterface.UpdateScaleCalls())
func (mock *replicaSetInterfaceMock) UpdateScaleCalls() []struct {
	Ctx            context.Context
	ReplicaSetName string
	Scale          *v1.Scale
	Opts           metav1.UpdateOptions
} {
	var calls []struct {
		Ctx            context.Context
		ReplicaSetName string
		Scale          *v1.Scale
		Opts           metav1.UpdateOptions
	}
	mock.lockUpdateScale.RLock()
	calls = mock.calls.UpdateScale
	mock.lockUpdateScale.RUnlock()
	return calls
}

// UpdateStatus calls UpdateStatusFunc.
func (mock *replicaSetInterfaceMock) UpdateStatus(ctx context.Context, replicaSet *appsv1.ReplicaSet, opts metav1.UpdateOptions) (*appsv1.ReplicaSet, error) {
	if mock.UpdateStatusFunc == nil {
		panic("replicaSetInterfaceMock.UpdateStatusFunc: method is nil but replicaSetInterface.UpdateStatus was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ReplicaSet *appsv1.ReplicaSet
		Opts       metav1.UpdateOptions
	}{
		Ctx:        ctx,
		ReplicaSet: replicaSet,
		Opts:       opts,
	}
	mock.lockUpdateStatus.Lock()
	mock.calls.UpdateStatus = append(mock.calls.UpdateStatus, callInfo)
	mock.lockUpdateStatus.Unlock()
	return mock.UpdateStatusFunc(ctx, replicaSet, opts)
}

// UpdateStatusCalls gets all the calls that were made to UpdateStatus.
// Check the length with:
//     len(mockedreplicaSetInterface.UpdateStatusCalls())
func (mock *replicaSetInterfaceMock) UpdateStatusCalls() []struct {
	Ctx        context.Context
	ReplicaSet *appsv1.ReplicaSet
	Opts       metav1.UpdateOptions
} {
	var calls []struct {
		Ctx        context.Context
		ReplicaSet *appsv1.ReplicaSet
		Opts       metav1.UpdateOptions
	}
	mock.lockUpdateStatus.RLock()
	calls = mock.calls.UpdateStatus
	mock.lockUpdateStatus.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *replicaSetInterfaceMock) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	if mock.WatchFunc == nil {
		panic("replicaSetInterfaceMock.WatchFunc: method is nil but replicaSetInterface.Watch was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	mock.lockWatch.Unlock()
	return mock.WatchFunc(ctx, opts)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//     len(mockedreplicaSetInterface.WatchCalls())
func (mock *replicaSetInterfaceMock) WatchCalls() []struct {
	Ctx  context.Context
	Opts metav1.ListOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}
	mock.lockWatch.RLock()
	calls = mock.calls.Watch
	mock.lockWatch.RUnlock()
	return calls
}
