// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package livelint_test

import (
	"context"
	"github.com/bespinian/livelint/internal/livelint"
	apiappsv1 "k8s.io/api/apps/v1"
	"k8s.io/api/autoscaling/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	applyconfigurationsappsv1 "k8s.io/client-go/applyconfigurations/apps/v1"
	autoscalingv1 "k8s.io/client-go/applyconfigurations/autoscaling/v1"
	"sync"
)

// Ensure, that ReplicaSetInterfaceMock does implement livelint.ReplicaSetInterface.
// If this is not the case, regenerate this file with moq.
var _ livelint.ReplicaSetInterface = &ReplicaSetInterfaceMock{}

// ReplicaSetInterfaceMock is a mock implementation of livelint.ReplicaSetInterface.
//
//	func TestSomethingThatUsesReplicaSetInterface(t *testing.T) {
//
//		// make and configure a mocked livelint.ReplicaSetInterface
//		mockedReplicaSetInterface := &ReplicaSetInterfaceMock{
//			ApplyFunc: func(ctx context.Context, replicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*apiappsv1.ReplicaSet, error) {
//				panic("mock out the Apply method")
//			},
//			ApplyScaleFunc: func(ctx context.Context, replicaSetName string, scale *autoscalingv1.ScaleApplyConfiguration, opts metav1.ApplyOptions) (*v1.Scale, error) {
//				panic("mock out the ApplyScale method")
//			},
//			ApplyStatusFunc: func(ctx context.Context, replicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*apiappsv1.ReplicaSet, error) {
//				panic("mock out the ApplyStatus method")
//			},
//			CreateFunc: func(ctx context.Context, replicaSet *apiappsv1.ReplicaSet, opts metav1.CreateOptions) (*apiappsv1.ReplicaSet, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, name string, opts metav1.DeleteOptions) error {
//				panic("mock out the Delete method")
//			},
//			DeleteCollectionFunc: func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
//				panic("mock out the DeleteCollection method")
//			},
//			GetFunc: func(ctx context.Context, name string, opts metav1.GetOptions) (*apiappsv1.ReplicaSet, error) {
//				panic("mock out the Get method")
//			},
//			GetScaleFunc: func(ctx context.Context, replicaSetName string, options metav1.GetOptions) (*v1.Scale, error) {
//				panic("mock out the GetScale method")
//			},
//			ListFunc: func(ctx context.Context, opts metav1.ListOptions) (*apiappsv1.ReplicaSetList, error) {
//				panic("mock out the List method")
//			},
//			PatchFunc: func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*apiappsv1.ReplicaSet, error) {
//				panic("mock out the Patch method")
//			},
//			UpdateFunc: func(ctx context.Context, replicaSet *apiappsv1.ReplicaSet, opts metav1.UpdateOptions) (*apiappsv1.ReplicaSet, error) {
//				panic("mock out the Update method")
//			},
//			UpdateScaleFunc: func(ctx context.Context, replicaSetName string, scale *v1.Scale, opts metav1.UpdateOptions) (*v1.Scale, error) {
//				panic("mock out the UpdateScale method")
//			},
//			UpdateStatusFunc: func(ctx context.Context, replicaSet *apiappsv1.ReplicaSet, opts metav1.UpdateOptions) (*apiappsv1.ReplicaSet, error) {
//				panic("mock out the UpdateStatus method")
//			},
//			WatchFunc: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
//				panic("mock out the Watch method")
//			},
//		}
//
//		// use mockedReplicaSetInterface in code that requires livelint.ReplicaSetInterface
//		// and then make assertions.
//
//	}
type ReplicaSetInterfaceMock struct {
	// ApplyFunc mocks the Apply method.
	ApplyFunc func(ctx context.Context, replicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*apiappsv1.ReplicaSet, error)

	// ApplyScaleFunc mocks the ApplyScale method.
	ApplyScaleFunc func(ctx context.Context, replicaSetName string, scale *autoscalingv1.ScaleApplyConfiguration, opts metav1.ApplyOptions) (*v1.Scale, error)

	// ApplyStatusFunc mocks the ApplyStatus method.
	ApplyStatusFunc func(ctx context.Context, replicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*apiappsv1.ReplicaSet, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, replicaSet *apiappsv1.ReplicaSet, opts metav1.CreateOptions) (*apiappsv1.ReplicaSet, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, name string, opts metav1.DeleteOptions) error

	// DeleteCollectionFunc mocks the DeleteCollection method.
	DeleteCollectionFunc func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, name string, opts metav1.GetOptions) (*apiappsv1.ReplicaSet, error)

	// GetScaleFunc mocks the GetScale method.
	GetScaleFunc func(ctx context.Context, replicaSetName string, options metav1.GetOptions) (*v1.Scale, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, opts metav1.ListOptions) (*apiappsv1.ReplicaSetList, error)

	// PatchFunc mocks the Patch method.
	PatchFunc func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*apiappsv1.ReplicaSet, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, replicaSet *apiappsv1.ReplicaSet, opts metav1.UpdateOptions) (*apiappsv1.ReplicaSet, error)

	// UpdateScaleFunc mocks the UpdateScale method.
	UpdateScaleFunc func(ctx context.Context, replicaSetName string, scale *v1.Scale, opts metav1.UpdateOptions) (*v1.Scale, error)

	// UpdateStatusFunc mocks the UpdateStatus method.
	UpdateStatusFunc func(ctx context.Context, replicaSet *apiappsv1.ReplicaSet, opts metav1.UpdateOptions) (*apiappsv1.ReplicaSet, error)

	// WatchFunc mocks the Watch method.
	WatchFunc func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)

	// calls tracks calls to the methods.
	calls struct {
		// Apply holds details about calls to the Apply method.
		Apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSet is the replicaSet argument value.
			ReplicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration
			// Opts is the opts argument value.
			Opts metav1.ApplyOptions
		}
		// ApplyScale holds details about calls to the ApplyScale method.
		ApplyScale []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSetName is the replicaSetName argument value.
			ReplicaSetName string
			// Scale is the scale argument value.
			Scale *autoscalingv1.ScaleApplyConfiguration
			// Opts is the opts argument value.
			Opts metav1.ApplyOptions
		}
		// ApplyStatus holds details about calls to the ApplyStatus method.
		ApplyStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSet is the replicaSet argument value.
			ReplicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration
			// Opts is the opts argument value.
			Opts metav1.ApplyOptions
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSet is the replicaSet argument value.
			ReplicaSet *apiappsv1.ReplicaSet
			// Opts is the opts argument value.
			Opts metav1.CreateOptions
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts metav1.DeleteOptions
		}
		// DeleteCollection holds details about calls to the DeleteCollection method.
		DeleteCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.DeleteOptions
			// ListOpts is the listOpts argument value.
			ListOpts metav1.ListOptions
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts metav1.GetOptions
		}
		// GetScale holds details about calls to the GetScale method.
		GetScale []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSetName is the replicaSetName argument value.
			ReplicaSetName string
			// Options is the options argument value.
			Options metav1.GetOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.ListOptions
		}
		// Patch holds details about calls to the Patch method.
		Patch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Pt is the pt argument value.
			Pt types.PatchType
			// Data is the data argument value.
			Data []byte
			// Opts is the opts argument value.
			Opts metav1.PatchOptions
			// Subresources is the subresources argument value.
			Subresources []string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSet is the replicaSet argument value.
			ReplicaSet *apiappsv1.ReplicaSet
			// Opts is the opts argument value.
			Opts metav1.UpdateOptions
		}
		// UpdateScale holds details about calls to the UpdateScale method.
		UpdateScale []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSetName is the replicaSetName argument value.
			ReplicaSetName string
			// Scale is the scale argument value.
			Scale *v1.Scale
			// Opts is the opts argument value.
			Opts metav1.UpdateOptions
		}
		// UpdateStatus holds details about calls to the UpdateStatus method.
		UpdateStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReplicaSet is the replicaSet argument value.
			ReplicaSet *apiappsv1.ReplicaSet
			// Opts is the opts argument value.
			Opts metav1.UpdateOptions
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts metav1.ListOptions
		}
	}
	lockApply            sync.RWMutex
	lockApplyScale       sync.RWMutex
	lockApplyStatus      sync.RWMutex
	lockCreate           sync.RWMutex
	lockDelete           sync.RWMutex
	lockDeleteCollection sync.RWMutex
	lockGet              sync.RWMutex
	lockGetScale         sync.RWMutex
	lockList             sync.RWMutex
	lockPatch            sync.RWMutex
	lockUpdate           sync.RWMutex
	lockUpdateScale      sync.RWMutex
	lockUpdateStatus     sync.RWMutex
	lockWatch            sync.RWMutex
}

// Apply calls ApplyFunc.
func (mock *ReplicaSetInterfaceMock) Apply(ctx context.Context, replicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*apiappsv1.ReplicaSet, error) {
	if mock.ApplyFunc == nil {
		panic("ReplicaSetInterfaceMock.ApplyFunc: method is nil but ReplicaSetInterface.Apply was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ReplicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration
		Opts       metav1.ApplyOptions
	}{
		Ctx:        ctx,
		ReplicaSet: replicaSet,
		Opts:       opts,
	}
	mock.lockApply.Lock()
	mock.calls.Apply = append(mock.calls.Apply, callInfo)
	mock.lockApply.Unlock()
	return mock.ApplyFunc(ctx, replicaSet, opts)
}

// ApplyCalls gets all the calls that were made to Apply.
// Check the length with:
//
//	len(mockedReplicaSetInterface.ApplyCalls())
func (mock *ReplicaSetInterfaceMock) ApplyCalls() []struct {
	Ctx        context.Context
	ReplicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration
	Opts       metav1.ApplyOptions
} {
	var calls []struct {
		Ctx        context.Context
		ReplicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration
		Opts       metav1.ApplyOptions
	}
	mock.lockApply.RLock()
	calls = mock.calls.Apply
	mock.lockApply.RUnlock()
	return calls
}

// ApplyScale calls ApplyScaleFunc.
func (mock *ReplicaSetInterfaceMock) ApplyScale(ctx context.Context, replicaSetName string, scale *autoscalingv1.ScaleApplyConfiguration, opts metav1.ApplyOptions) (*v1.Scale, error) {
	if mock.ApplyScaleFunc == nil {
		panic("ReplicaSetInterfaceMock.ApplyScaleFunc: method is nil but ReplicaSetInterface.ApplyScale was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ReplicaSetName string
		Scale          *autoscalingv1.ScaleApplyConfiguration
		Opts           metav1.ApplyOptions
	}{
		Ctx:            ctx,
		ReplicaSetName: replicaSetName,
		Scale:          scale,
		Opts:           opts,
	}
	mock.lockApplyScale.Lock()
	mock.calls.ApplyScale = append(mock.calls.ApplyScale, callInfo)
	mock.lockApplyScale.Unlock()
	return mock.ApplyScaleFunc(ctx, replicaSetName, scale, opts)
}

// ApplyScaleCalls gets all the calls that were made to ApplyScale.
// Check the length with:
//
//	len(mockedReplicaSetInterface.ApplyScaleCalls())
func (mock *ReplicaSetInterfaceMock) ApplyScaleCalls() []struct {
	Ctx            context.Context
	ReplicaSetName string
	Scale          *autoscalingv1.ScaleApplyConfiguration
	Opts           metav1.ApplyOptions
} {
	var calls []struct {
		Ctx            context.Context
		ReplicaSetName string
		Scale          *autoscalingv1.ScaleApplyConfiguration
		Opts           metav1.ApplyOptions
	}
	mock.lockApplyScale.RLock()
	calls = mock.calls.ApplyScale
	mock.lockApplyScale.RUnlock()
	return calls
}

// ApplyStatus calls ApplyStatusFunc.
func (mock *ReplicaSetInterfaceMock) ApplyStatus(ctx context.Context, replicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration, opts metav1.ApplyOptions) (*apiappsv1.ReplicaSet, error) {
	if mock.ApplyStatusFunc == nil {
		panic("ReplicaSetInterfaceMock.ApplyStatusFunc: method is nil but ReplicaSetInterface.ApplyStatus was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ReplicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration
		Opts       metav1.ApplyOptions
	}{
		Ctx:        ctx,
		ReplicaSet: replicaSet,
		Opts:       opts,
	}
	mock.lockApplyStatus.Lock()
	mock.calls.ApplyStatus = append(mock.calls.ApplyStatus, callInfo)
	mock.lockApplyStatus.Unlock()
	return mock.ApplyStatusFunc(ctx, replicaSet, opts)
}

// ApplyStatusCalls gets all the calls that were made to ApplyStatus.
// Check the length with:
//
//	len(mockedReplicaSetInterface.ApplyStatusCalls())
func (mock *ReplicaSetInterfaceMock) ApplyStatusCalls() []struct {
	Ctx        context.Context
	ReplicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration
	Opts       metav1.ApplyOptions
} {
	var calls []struct {
		Ctx        context.Context
		ReplicaSet *applyconfigurationsappsv1.ReplicaSetApplyConfiguration
		Opts       metav1.ApplyOptions
	}
	mock.lockApplyStatus.RLock()
	calls = mock.calls.ApplyStatus
	mock.lockApplyStatus.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *ReplicaSetInterfaceMock) Create(ctx context.Context, replicaSet *apiappsv1.ReplicaSet, opts metav1.CreateOptions) (*apiappsv1.ReplicaSet, error) {
	if mock.CreateFunc == nil {
		panic("ReplicaSetInterfaceMock.CreateFunc: method is nil but ReplicaSetInterface.Create was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ReplicaSet *apiappsv1.ReplicaSet
		Opts       metav1.CreateOptions
	}{
		Ctx:        ctx,
		ReplicaSet: replicaSet,
		Opts:       opts,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, replicaSet, opts)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedReplicaSetInterface.CreateCalls())
func (mock *ReplicaSetInterfaceMock) CreateCalls() []struct {
	Ctx        context.Context
	ReplicaSet *apiappsv1.ReplicaSet
	Opts       metav1.CreateOptions
} {
	var calls []struct {
		Ctx        context.Context
		ReplicaSet *apiappsv1.ReplicaSet
		Opts       metav1.CreateOptions
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ReplicaSetInterfaceMock) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	if mock.DeleteFunc == nil {
		panic("ReplicaSetInterfaceMock.DeleteFunc: method is nil but ReplicaSetInterface.Delete was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Opts metav1.DeleteOptions
	}{
		Ctx:  ctx,
		Name: name,
		Opts: opts,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, name, opts)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedReplicaSetInterface.DeleteCalls())
func (mock *ReplicaSetInterfaceMock) DeleteCalls() []struct {
	Ctx  context.Context
	Name string
	Opts metav1.DeleteOptions
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Opts metav1.DeleteOptions
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeleteCollection calls DeleteCollectionFunc.
func (mock *ReplicaSetInterfaceMock) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	if mock.DeleteCollectionFunc == nil {
		panic("ReplicaSetInterfaceMock.DeleteCollectionFunc: method is nil but ReplicaSetInterface.DeleteCollection was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Opts     metav1.DeleteOptions
		ListOpts metav1.ListOptions
	}{
		Ctx:      ctx,
		Opts:     opts,
		ListOpts: listOpts,
	}
	mock.lockDeleteCollection.Lock()
	mock.calls.DeleteCollection = append(mock.calls.DeleteCollection, callInfo)
	mock.lockDeleteCollection.Unlock()
	return mock.DeleteCollectionFunc(ctx, opts, listOpts)
}

// DeleteCollectionCalls gets all the calls that were made to DeleteCollection.
// Check the length with:
//
//	len(mockedReplicaSetInterface.DeleteCollectionCalls())
func (mock *ReplicaSetInterfaceMock) DeleteCollectionCalls() []struct {
	Ctx      context.Context
	Opts     metav1.DeleteOptions
	ListOpts metav1.ListOptions
} {
	var calls []struct {
		Ctx      context.Context
		Opts     metav1.DeleteOptions
		ListOpts metav1.ListOptions
	}
	mock.lockDeleteCollection.RLock()
	calls = mock.calls.DeleteCollection
	mock.lockDeleteCollection.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ReplicaSetInterfaceMock) Get(ctx context.Context, name string, opts metav1.GetOptions) (*apiappsv1.ReplicaSet, error) {
	if mock.GetFunc == nil {
		panic("ReplicaSetInterfaceMock.GetFunc: method is nil but ReplicaSetInterface.Get was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Opts metav1.GetOptions
	}{
		Ctx:  ctx,
		Name: name,
		Opts: opts,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, name, opts)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedReplicaSetInterface.GetCalls())
func (mock *ReplicaSetInterfaceMock) GetCalls() []struct {
	Ctx  context.Context
	Name string
	Opts metav1.GetOptions
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Opts metav1.GetOptions
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetScale calls GetScaleFunc.
func (mock *ReplicaSetInterfaceMock) GetScale(ctx context.Context, replicaSetName string, options metav1.GetOptions) (*v1.Scale, error) {
	if mock.GetScaleFunc == nil {
		panic("ReplicaSetInterfaceMock.GetScaleFunc: method is nil but ReplicaSetInterface.GetScale was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ReplicaSetName string
		Options        metav1.GetOptions
	}{
		Ctx:            ctx,
		ReplicaSetName: replicaSetName,
		Options:        options,
	}
	mock.lockGetScale.Lock()
	mock.calls.GetScale = append(mock.calls.GetScale, callInfo)
	mock.lockGetScale.Unlock()
	return mock.GetScaleFunc(ctx, replicaSetName, options)
}

// GetScaleCalls gets all the calls that were made to GetScale.
// Check the length with:
//
//	len(mockedReplicaSetInterface.GetScaleCalls())
func (mock *ReplicaSetInterfaceMock) GetScaleCalls() []struct {
	Ctx            context.Context
	ReplicaSetName string
	Options        metav1.GetOptions
} {
	var calls []struct {
		Ctx            context.Context
		ReplicaSetName string
		Options        metav1.GetOptions
	}
	mock.lockGetScale.RLock()
	calls = mock.calls.GetScale
	mock.lockGetScale.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ReplicaSetInterfaceMock) List(ctx context.Context, opts metav1.ListOptions) (*apiappsv1.ReplicaSetList, error) {
	if mock.ListFunc == nil {
		panic("ReplicaSetInterfaceMock.ListFunc: method is nil but ReplicaSetInterface.List was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, opts)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedReplicaSetInterface.ListCalls())
func (mock *ReplicaSetInterfaceMock) ListCalls() []struct {
	Ctx  context.Context
	Opts metav1.ListOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Patch calls PatchFunc.
func (mock *ReplicaSetInterfaceMock) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*apiappsv1.ReplicaSet, error) {
	if mock.PatchFunc == nil {
		panic("ReplicaSetInterfaceMock.PatchFunc: method is nil but ReplicaSetInterface.Patch was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Name         string
		Pt           types.PatchType
		Data         []byte
		Opts         metav1.PatchOptions
		Subresources []string
	}{
		Ctx:          ctx,
		Name:         name,
		Pt:           pt,
		Data:         data,
		Opts:         opts,
		Subresources: subresources,
	}
	mock.lockPatch.Lock()
	mock.calls.Patch = append(mock.calls.Patch, callInfo)
	mock.lockPatch.Unlock()
	return mock.PatchFunc(ctx, name, pt, data, opts, subresources...)
}

// PatchCalls gets all the calls that were made to Patch.
// Check the length with:
//
//	len(mockedReplicaSetInterface.PatchCalls())
func (mock *ReplicaSetInterfaceMock) PatchCalls() []struct {
	Ctx          context.Context
	Name         string
	Pt           types.PatchType
	Data         []byte
	Opts         metav1.PatchOptions
	Subresources []string
} {
	var calls []struct {
		Ctx          context.Context
		Name         string
		Pt           types.PatchType
		Data         []byte
		Opts         metav1.PatchOptions
		Subresources []string
	}
	mock.lockPatch.RLock()
	calls = mock.calls.Patch
	mock.lockPatch.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ReplicaSetInterfaceMock) Update(ctx context.Context, replicaSet *apiappsv1.ReplicaSet, opts metav1.UpdateOptions) (*apiappsv1.ReplicaSet, error) {
	if mock.UpdateFunc == nil {
		panic("ReplicaSetInterfaceMock.UpdateFunc: method is nil but ReplicaSetInterface.Update was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ReplicaSet *apiappsv1.ReplicaSet
		Opts       metav1.UpdateOptions
	}{
		Ctx:        ctx,
		ReplicaSet: replicaSet,
		Opts:       opts,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, replicaSet, opts)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedReplicaSetInterface.UpdateCalls())
func (mock *ReplicaSetInterfaceMock) UpdateCalls() []struct {
	Ctx        context.Context
	ReplicaSet *apiappsv1.ReplicaSet
	Opts       metav1.UpdateOptions
} {
	var calls []struct {
		Ctx        context.Context
		ReplicaSet *apiappsv1.ReplicaSet
		Opts       metav1.UpdateOptions
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdateScale calls UpdateScaleFunc.
func (mock *ReplicaSetInterfaceMock) UpdateScale(ctx context.Context, replicaSetName string, scale *v1.Scale, opts metav1.UpdateOptions) (*v1.Scale, error) {
	if mock.UpdateScaleFunc == nil {
		panic("ReplicaSetInterfaceMock.UpdateScaleFunc: method is nil but ReplicaSetInterface.UpdateScale was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ReplicaSetName string
		Scale          *v1.Scale
		Opts           metav1.UpdateOptions
	}{
		Ctx:            ctx,
		ReplicaSetName: replicaSetName,
		Scale:          scale,
		Opts:           opts,
	}
	mock.lockUpdateScale.Lock()
	mock.calls.UpdateScale = append(mock.calls.UpdateScale, callInfo)
	mock.lockUpdateScale.Unlock()
	return mock.UpdateScaleFunc(ctx, replicaSetName, scale, opts)
}

// UpdateScaleCalls gets all the calls that were made to UpdateScale.
// Check the length with:
//
//	len(mockedReplicaSetInterface.UpdateScaleCalls())
func (mock *ReplicaSetInterfaceMock) UpdateScaleCalls() []struct {
	Ctx            context.Context
	ReplicaSetName string
	Scale          *v1.Scale
	Opts           metav1.UpdateOptions
} {
	var calls []struct {
		Ctx            context.Context
		ReplicaSetName string
		Scale          *v1.Scale
		Opts           metav1.UpdateOptions
	}
	mock.lockUpdateScale.RLock()
	calls = mock.calls.UpdateScale
	mock.lockUpdateScale.RUnlock()
	return calls
}

// UpdateStatus calls UpdateStatusFunc.
func (mock *ReplicaSetInterfaceMock) UpdateStatus(ctx context.Context, replicaSet *apiappsv1.ReplicaSet, opts metav1.UpdateOptions) (*apiappsv1.ReplicaSet, error) {
	if mock.UpdateStatusFunc == nil {
		panic("ReplicaSetInterfaceMock.UpdateStatusFunc: method is nil but ReplicaSetInterface.UpdateStatus was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ReplicaSet *apiappsv1.ReplicaSet
		Opts       metav1.UpdateOptions
	}{
		Ctx:        ctx,
		ReplicaSet: replicaSet,
		Opts:       opts,
	}
	mock.lockUpdateStatus.Lock()
	mock.calls.UpdateStatus = append(mock.calls.UpdateStatus, callInfo)
	mock.lockUpdateStatus.Unlock()
	return mock.UpdateStatusFunc(ctx, replicaSet, opts)
}

// UpdateStatusCalls gets all the calls that were made to UpdateStatus.
// Check the length with:
//
//	len(mockedReplicaSetInterface.UpdateStatusCalls())
func (mock *ReplicaSetInterfaceMock) UpdateStatusCalls() []struct {
	Ctx        context.Context
	ReplicaSet *apiappsv1.ReplicaSet
	Opts       metav1.UpdateOptions
} {
	var calls []struct {
		Ctx        context.Context
		ReplicaSet *apiappsv1.ReplicaSet
		Opts       metav1.UpdateOptions
	}
	mock.lockUpdateStatus.RLock()
	calls = mock.calls.UpdateStatus
	mock.lockUpdateStatus.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *ReplicaSetInterfaceMock) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	if mock.WatchFunc == nil {
		panic("ReplicaSetInterfaceMock.WatchFunc: method is nil but ReplicaSetInterface.Watch was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	mock.lockWatch.Unlock()
	return mock.WatchFunc(ctx, opts)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//
//	len(mockedReplicaSetInterface.WatchCalls())
func (mock *ReplicaSetInterfaceMock) WatchCalls() []struct {
	Ctx  context.Context
	Opts metav1.ListOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts metav1.ListOptions
	}
	mock.lockWatch.RLock()
	calls = mock.calls.Watch
	mock.lockWatch.RUnlock()
	return calls
}
