name: Lint and Test

on: [push, pull_request]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46
          args: --timeout=5m
      - name: Run tests
        run: make test
      - name: Get Hash
        id: githash
        run: echo "git_hash=$(git rev-parse --short HEAD)" >> $GITHUB_HASH
      - name: Check Hash
        run: echo "${{ env.githash }}"
      - name: Get Tag
        id: gittag
        run: echo "git_hash=$(git tag --points-at HEAD")" >> $GITHUB_TAG
      - name: Check Hash
        run: echo "${{ env.gittag }}"
      - name: Build date
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_BUILD_DATE
      - name: Build application
        run: go build -o bin/livelint -ldflags "-X main.githash="$GITHUB_SHA" -X main.date=$GITHUB_BUILD_DATE -X main.gittag=$GITHUB_TAG"
  release:
    name: Release
    needs: verify
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Release
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
