name: Lint and Test

on:
  push:

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: --timeout=5m
      - name: Run tests
        run: make test
      - name: Build application
        run: make build
  release:
    name: Release
    needs: verify
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
