name: Lint and Test

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Lint code
        uses: golangci/golangci-lint-action@v3
      - name: Run tests
        run: make test
      - name: Build application
        run: make build
